export enum EpicField {
  TITLE = 'Title',
  STATUS = 'Status',
  LABELS = 'Labels',
  PERIOD = 'Period',
  SPRINT = 'Sprint',
  SPRINT_POINTS = 'Sprint points',
  REPOSITORY = 'Repository',
  ASSIGNEES = 'Assignees',
  EPIC_POINTS = 'Epic points',
  EPIC_POINTS_REMAINING = 'Epic points - remaining',
  EPIC_POINTS_DONE = 'Epic points - done',
  PARTNER = 'Partner',
  TYPE = 'Type',
  RELEASE = 'Release',
  MILESTONE = 'Milestone',
  QUARTILE = 'Quartile',
  TYPE_ALKEMIO = 'Type (Alkemio)',
  NON_FUNCTIONAL_AREA = 'Non-functional area',
  FUNCTIONAL_AREA = 'Functional area',
  FEATURE = 'Feature',
  FEATURE_2 = 'Feature 2',
  ORDER = 'Order',
  NEW_IMPROVEMENT = 'New / Improvement',
  CLASSIFICATION = 'Classification',
}
