export enum EpicField {
  TITLE = 'Title',
  STATUS = 'Status',
  LABELS = 'Labels',
  PERIOD = 'Period',
  SPRINT = 'Sprint',
  SPRINT_POINTS = 'Sprint points',
  REPOSITORY = 'Repository',
  ASSIGNEES = 'Assignees',
  EPIC_POINTS = 'Epic points',
  EPIC_POINTS_REMAINING = 'Epic points - remaining',
  PARTNER = 'Partner',
  TYPE = 'Type',
  RELEASE = 'Release',
  Milestone = 'Milestone',
}
