export enum EpicField {
  TITLE = 'Title',
  STATUS = 'Status',
  LABELS = 'Labels',
  PERIOD = 'Period',
  SPRINT = 'Sprint',
  SPRINT_POINTS = 'Sprint points',
  REPOSITORY = 'Repository',
  ASSIGNEES = 'Assignees',
  EPIC_POINTS = 'Epic points',
  EPIC_POINTS_REMAINING = 'Epic points - remaining',
  EPIC_POINTS_DONE = 'Epic points - done',
  PARTNER = 'Partner',
  TYPE = 'Type',
  RELEASE = 'Release',
  MILESTONE = 'Milestone',
  QUARTILE = 'Quartile',
  TYPE_ALKEMIO = 'Type (Alkemio)',
  NON_FUNCTIONAL_AREA = 'Non-functional area',
  FUNCTIONAL_AREA = 'Functional area',
  FEATURE = 'Feature',
  FEATURE_2 = 'Feature 2',
  ORDER = 'Order',
  NEW_IMPROVEMENT = 'New / Improvement',
  CLASSIFICATION = 'Classification',
}

// Defines the fixed column order for capacity planning export.
// Adjust this array to reorder columns in the Excel output.
export const CAPACITY_PLANNING_COLUMN_ORDER: string[] = [
  EpicField.TITLE,
  EpicField.QUARTILE,
  EpicField.CLASSIFICATION,
  EpicField.EPIC_POINTS,
  EpicField.STATUS,
  EpicField.TYPE_ALKEMIO,
  EpicField.LABELS,
  EpicField.PARTNER,
  EpicField.TYPE,
  EpicField.NEW_IMPROVEMENT,
  EpicField.FEATURE,
  EpicField.FEATURE_2,
  EpicField.FUNCTIONAL_AREA,
  EpicField.NON_FUNCTIONAL_AREA,
  EpicField.PERIOD,
  EpicField.SPRINT,
  EpicField.SPRINT_POINTS,
  EpicField.RELEASE,
  EpicField.MILESTONE,
  EpicField.REPOSITORY,
  EpicField.ASSIGNEES,
  EpicField.ORDER, // keep ordering / priority first if desired
  EpicField.EPIC_POINTS_REMAINING,
  EpicField.EPIC_POINTS_DONE,
];
